times = ('Palmeiras', 'São Paulo', 'Corinthians', 'Bahia', 'Fluminense', 'Athletico-PR', 'Bragantino', 'Grêmio', 'Chapecoense', 'Mirassol', 'Flamengo', 'Coritiba', 'Botafogo', 'Vitória', 'Remo', 'Atlético-MG', 'Vasco', 'Santos', 'Internacional', 'Cruzeiro')
print('-' * 60)
print(f'Os 5 primeiros colocados são: {times[:6]}')
print('-' * 60)
print(f'Os 4 últimos são: {times[-4:]}')
print('-' * 60)
print(f'Times em ordem alfabética: {sorted(times)}')
print('-' * 60)
print(f'A Chapecoense está na {times.index('Chapecoense')+1}ª posição')
